spring:

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # create-drop : SessionFactory ? ???? drop, create, alter ?? ??? ? drop
      ddl-auto: create-drop
    properties:
      # ????? query ?? ?? ?? ???? ??.
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

jwt:
  header: Authorization
  #HS512 ????? ??? ??? ??? 512bit, ? 64byte ??? secret key? ???? ??.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  #~$openssl rand -hex 64
  #? ???
  secret: 1cea25ae8586cdf524b3647f75b7c6941c71a721aa3a4200f959bc6404c2d559c89f1bb82a2dcaa38f02c0c780ecaaececf87d44ac13f0a7394ccc2323631b33
  token-validity-in-seconds: 86400

logging:
  level:
    com.andy: DEBUG